spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
# eureka:
  # instance:
    # prefer-ip-address: true
    # instance-id: 
  # client:
    # serviceUrl:
      # defaultZone: http://localhost:8070/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking cafe Cereza

build:
  version: "1.0"

account:
  message: "Welcome to Coffee prod"
  details:
    name: "bob"
    email: "toto.tit@ac.fr"
  phone:
    - 2003040506
    - 0107080901
